version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prestamo
      - POSTGRES_USER=postgres
    container_name: database
    volumes:
      - ./postgres:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - DB_PASSWORD=postgres
      - DB_NAME=prestamo
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_TYPE=postgres
      - PORT=3000
      - DB_SINCRONIZE=true
      - JWT_SECRET=myseCret127
    ports:
      - '3000:3000'
    depends_on:
      - db